In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow
from tensorflow import keras

In [21]:
dataset = pd.read_csv('breast_cancer.csv', header = None)

In [22]:
dataset.head(5)

0  1  2  3  4   5  6  7  8  9
0  5  1  1  1  2   1  3  1  1  2
1  5  4  4  5  7  10  3  2  1  2
2  3  1  1  1  2   2  3  1  1  2
3  6  8  8  1  3   4  3  7  1  2
4  4  1  1  3  2   1  3  1  1  2

In [23]:
data = dataset.iloc[:,:-1]
labels = dataset.iloc[:,-1]

In [24]:
data

0   1   2  3  4   5   6   7  8
0    5   1   1  1  2   1   3   1  1
1    5   4   4  5  7  10   3   2  1
2    3   1   1  1  2   2   3   1  1
3    6   8   8  1  3   4   3   7  1
4    4   1   1  3  2   1   3   1  1
..  ..  ..  .. .. ..  ..  ..  .. ..
694  3   1   1  1  3   2   1   1  1
695  2   1   1  1  2   1   1   1  1
696  5  10  10  3  7   3   8  10  2
697  4   8   6  4  3   4  10   6  1
698  4   8   8  5  4   5  10   4  1

[699 rows x 9 columns]

In [25]:
labels

0      2
1      2
2      2
3      2
4      2
      ..
694    2
695    2
696    4
697    4
698    4
Name: 9, Length: 699, dtype: int64

In [26]:
data = data.replace('?', np.nan)

In [27]:
data.iloc[235,:]

0      3
1      1
2      4
3      1
4      2
5    NaN
6      3
7      1
8      1
Name: 235, dtype: object

In [28]:
data = data.fillna(0)

In [29]:
data.iloc[235,:]

0    3
1    1
2    4
3    1
4    2
5    0
6    3
7    1
8    1
Name: 235, dtype: object

In [30]:
from sklearn.preprocessing import normalize

data = normalize(data, axis = 0)

In [31]:
data

array([[0.03610697, 0.00864934, 0.0086529 , ..., 0.02692885, 0.0090336 ,
        0.01618174],
       [0.03610697, 0.03459736, 0.03461161, ..., 0.02692885, 0.01806721,
        0.01618174],
       [0.02166418, 0.00864934, 0.0086529 , ..., 0.02692885, 0.0090336 ,
        0.01618174],
       ...,
       [0.03610697, 0.08649341, 0.08652902, ..., 0.07181028, 0.09033604,
        0.03236348],
       [0.02888557, 0.06919473, 0.05191741, ..., 0.08976285, 0.05420163,
        0.01618174],
       [0.02888557, 0.06919473, 0.06922322, ..., 0.08976285, 0.03613442,
        0.01618174]])

In [32]:
labels = np.array(labels)

In [33]:
labels

array([2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 4, 4,
       2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 4, 2, 4, 4, 4,
       4, 2, 4, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 4,
       2, 4, 4, 2, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4,
       2, 4, 4, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2, 2,
       4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 4, 2,
       2, 4, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4,
       2, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 4, 2, 2, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2,
       2, 4, 4, 4, 4, 2, 4, 4, 2, 4, 4, 4, 2, 4, 2, 2, 4, 4, 4, 4, 2, 2,
       2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 4, 2, 2, 2, 2, 4, 4, 4, 4,
       4, 2, 4, 4, 4, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 4, 4,
       4, 2, 4, 4, 2, 2, 4, 4, 2, 4, 2, 2, 2, 4, 4,

In [34]:
labels = np.where(labels ==2, 0, 1)
labels

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,

In [35]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train , y_test = train_test_split(data, labels, test_size = 0.20, random_state = 42)


In [36]:
x_train.shape

(559, 9)

In [37]:
x_test.shape

(140, 9)

In [50]:
y_test

array([0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0])

In [40]:
from tensorflow.keras import Model, Input
from tensorflow.keras.layers import Dense, Dropout, Activation
from tensorflow.keras.callbacks import EarlyStopping

In [76]:
inputs = Input(shape =(9,))

for i in range(0,15):
    x = Dense(6)(inputs)
    x = Activation('relu')(x)
    x = Dense(4)(x)
    x = Activation('relu')(x)
    x = Dense(1)(x)
outputs = Activation('sigmoid')(x)

model = Model(inputs, outputs)

model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics =['accuracy'])

In [77]:
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 9)]               0         
_________________________________________________________________
dense_51 (Dense)             (None, 6)                 60        
_________________________________________________________________
activation_37 (Activation)   (None, 6)                 0         
_________________________________________________________________
dense_52 (Dense)             (None, 4)                 28        
_________________________________________________________________
activation_38 (Activation)   (None, 4)                 0         
_________________________________________________________________
dense_53 (Dense)             (None, 1)                 5         
_________________________________________________________________
activation_39 (Activation)   (None, 1)                 0   

In [78]:
callback = EarlyStopping(monitor='val_loss', patience=50)
history = model.fit(x_train, y_train, epochs=300, batch_size=5, 
                    validation_data= (x_test, y_test), callbacks =callback, verbose =1)

Epoch 1/300
112/112 [==============================] - 0s 3ms/step - loss: 0.6776 - accuracy: 0.6744 - val_loss: 0.6593 - val_accuracy: 0.6786
Epoch 2/300
112/112 [==============================] - 0s 3ms/step - loss: 0.6415 - accuracy: 0.6959 - val_loss: 0.6109 - val_accuracy: 0.7286
Epoch 3/300
112/112 [==============================] - 0s 2ms/step - loss: 0.5745 - accuracy: 0.7889 - val_loss: 0.5239 - val_accuracy: 0.8571
Epoch 4/300
112/112 [==============================] - 0s 2ms/step - loss: 0.4738 - accuracy: 0.8873 - val_loss: 0.4185 - val_accuracy: 0.9500
Epoch 5/300
112/112 [==============================] - 0s 2ms/step - loss: 0.3680 - accuracy: 0.9302 - val_loss: 0.3218 - val_accuracy: 0.9500
Epoch 6/300
112/112 [==============================] - 0s 2ms/step - loss: 0.2821 - accuracy: 0.9481 - val_loss: 0.2462 - val_accuracy: 0.9643
Epoch 7/300
112/112 [==============================] - 0s 3ms/step - loss: 0.2213 - accuracy: 0.9499 - val_loss: 0.1953 - val_accuracy: 0.9714

112/112 [==============================] - 0s 3ms/step - loss: 0.0842 - accuracy: 0.9696 - val_loss: 0.0740 - val_accuracy: 0.9643
Epoch 58/300
112/112 [==============================] - 0s 3ms/step - loss: 0.0842 - accuracy: 0.9696 - val_loss: 0.0701 - val_accuracy: 0.9643
Epoch 59/300
112/112 [==============================] - 0s 2ms/step - loss: 0.0848 - accuracy: 0.9696 - val_loss: 0.0705 - val_accuracy: 0.9643
Epoch 60/300
112/112 [==============================] - 0s 2ms/step - loss: 0.0857 - accuracy: 0.9678 - val_loss: 0.0715 - val_accuracy: 0.9643
Epoch 61/300
112/112 [==============================] - 0s 2ms/step - loss: 0.0839 - accuracy: 0.9678 - val_loss: 0.0697 - val_accuracy: 0.9643
Epoch 62/300
112/112 [==============================] - 0s 2ms/step - loss: 0.0837 - accuracy: 0.9696 - val_loss: 0.0733 - val_accuracy: 0.9643
Epoch 63/300
112/112 [==============================] - 0s 3ms/step - loss: 0.0833 - accuracy: 0.9696 - val_loss: 0.0703 - val_accuracy: 0.9643
Epoch

Epoch 114/300
112/112 [==============================] - 0s 2ms/step - loss: 0.0774 - accuracy: 0.9714 - val_loss: 0.0731 - val_accuracy: 0.9714
Epoch 115/300
112/112 [==============================] - 0s 2ms/step - loss: 0.0782 - accuracy: 0.9714 - val_loss: 0.0720 - val_accuracy: 0.9714
Epoch 116/300
112/112 [==============================] - 0s 2ms/step - loss: 0.0778 - accuracy: 0.9732 - val_loss: 0.0716 - val_accuracy: 0.9714
Epoch 117/300
112/112 [==============================] - 0s 3ms/step - loss: 0.0784 - accuracy: 0.9696 - val_loss: 0.0715 - val_accuracy: 0.9714
Epoch 118/300
112/112 [==============================] - 0s 3ms/step - loss: 0.0774 - accuracy: 0.9714 - val_loss: 0.0726 - val_accuracy: 0.9714
Epoch 119/300
112/112 [==============================] - 0s 2ms/step - loss: 0.0776 - accuracy: 0.9714 - val_loss: 0.0686 - val_accuracy: 0.9643
Epoch 120/300
112/112 [==============================] - 0s 2ms/step - loss: 0.0769 - accuracy: 0.9732 - val_loss: 0.0726 - val_ac

112/112 [==============================] - 0s 2ms/step - loss: 0.0746 - accuracy: 0.9750 - val_loss: 0.0735 - val_accuracy: 0.9643
Epoch 171/300
112/112 [==============================] - 0s 2ms/step - loss: 0.0737 - accuracy: 0.9714 - val_loss: 0.0721 - val_accuracy: 0.9714
Epoch 172/300
112/112 [==============================] - 0s 3ms/step - loss: 0.0748 - accuracy: 0.9714 - val_loss: 0.0693 - val_accuracy: 0.9714
Epoch 173/300
112/112 [==============================] - 0s 3ms/step - loss: 0.0753 - accuracy: 0.9732 - val_loss: 0.0699 - val_accuracy: 0.9714
Epoch 174/300
112/112 [==============================] - 0s 2ms/step - loss: 0.0746 - accuracy: 0.9714 - val_loss: 0.0677 - val_accuracy: 0.9714
Epoch 175/300
112/112 [==============================] - 0s 2ms/step - loss: 0.0754 - accuracy: 0.9714 - val_loss: 0.0688 - val_accuracy: 0.9714
Epoch 176/300
112/112 [==============================] - 0s 2ms/step - loss: 0.0746 - accuracy: 0.9732 - val_loss: 0.0714 - val_accuracy: 0.9714

In [79]:
result = model.predict(x_test)

In [80]:
result

array([[5.3554773e-04],
       [1.9041896e-03],
       [1.6575456e-03],
       [9.3493438e-01],
       [1.0307133e-03],
       [8.3613396e-04],
       [1.7803580e-02],
       [9.8948324e-01],
       [9.6913427e-01],
       [3.1044310e-01],
       [1.0773242e-03],
       [7.9783529e-01],
       [1.1535287e-03],
       [7.2399974e-03],
       [1.1535287e-03],
       [9.9780875e-01],
       [5.7739019e-04],
       [9.9842119e-01],
       [9.6502787e-01],
       [7.7694285e-01],
       [9.9993956e-01],
       [6.8125129e-04],
       [7.7872944e-01],
       [5.7739019e-04],
       [9.7399807e-01],
       [8.2477331e-03],
       [1.2350976e-03],
       [9.9269438e-01],
       [1.0634780e-02],
       [9.7609049e-01],
       [1.3384521e-03],
       [2.1730065e-03],
       [1.9041896e-03],
       [9.8373204e-01],
       [5.7739019e-04],
       [4.4792295e-03],
       [9.5859170e-04],
       [9.9993229e-01],
       [5.6603551e-04],
       [9.9353266e-01],
       [1.0773242e-03],
       [2.444744

In [81]:
result = np.where(result>=0.5, 1, 0)
result

array([[0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [64]:
result.shape

(140, 1)

In [82]:
result = result.reshape(result.shape[0])
result

array([0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0])

In [83]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print('accuracy = ',accuracy_score(y_test, result))

accuracy =  0.9714285714285714


In [84]:
pd.DataFrame(confusion_matrix(y_test, result))

0   1
0  94   1
1   3  42

In [85]:
print(classification_report(y_test, result))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98        95
           1       0.98      0.93      0.95        45

    accuracy                           0.97       140
   macro avg       0.97      0.96      0.97       140
weighted avg       0.97      0.97      0.97       140



In [86]:
print('biglearn.ir')

biglearn.ir
