## Environment

In [1]:
!pip install numpy

In [2]:
import numpy as np

## Ndarray Object

In [3]:
a=np.array([1,5,8])
a

array([1, 5, 8])

In [4]:
a.dtype

dtype('int32')

In [5]:
len(a)

3

In [10]:
a.size

3

In [13]:
a = np.array([1, 2, 3,4,5], ndmin = 2,dtype = np.int8) 
print (a)

[[1 2 3 4 5]]


In [17]:
a = np.array([[1, 2], [3, 4]],dtype=np.complex) 
print (a)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [18]:
a.shape

(2, 2)

In [20]:
a.itemsize

16

In [25]:
# dtype of array is int8 (1 byte) 
x = np.array([1,2,3,4,5], dtype = np.int32) 
print (x.itemsize)

4


## Array Creation Routines

In [31]:
np.empty([3,2]) 


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
np.zeros((5,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [33]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [35]:
np.identity((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.full((3,4),46546)

array([[46546, 46546, 46546, 46546],
       [46546, 46546, 46546, 46546],
       [46546, 46546, 46546, 46546]])

In [39]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Array From Existing Data

In [40]:
x = [1,2,3]  #list
a = np.asarray(x) 
print (a)

[1 2 3]


In [41]:
x = [1,2,3]
a = np.asarray(x, dtype = float) 
print (a)

[1. 2. 3.]


In [42]:
x = (1,2,3) #tuple
a = np.asarray(x) 
print (a)

[1 2 3]


In [43]:
x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print (a)

[(1, 2, 3) (4, 5)]


## Array From Numerical Ranges

In [60]:
np.array(range(11))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
x = np.arange(10,20,2) 
print (x)

[10 12 14 16 18]


In [62]:
x = np.linspace(10,20,5) 
x

array([10. , 12.5, 15. , 17.5, 20. ])

In [63]:
x = np.linspace(10,20, 5, endpoint = False) 
x

array([10., 12., 14., 16., 18.])

In [65]:
x = np.linspace(10,30,5, retstep = True) 
x

(array([10., 15., 20., 25., 30.]), 5.0)

In [67]:
a = np.logspace(23,105,num = 10, base = 2) 
a

array([8.38860800e+06, 4.63882126e+09, 2.56522449e+12, 1.41854499e+15,
       7.84442027e+17, 4.33789057e+20, 2.39881265e+23, 1.32652081e+26,
       7.33553522e+28, 4.05648192e+31])

## Indexing & Slicing

In [68]:
a = np.arange(10) 
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
a[2]

2

In [70]:
a[2:5]

array([2, 3, 4])

In [71]:
a[1:9]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
a[2:7:3] 

array([2, 5])

In [75]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a) 

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [78]:
a[1,2]

5

In [79]:
a[1,:]

array([3, 4, 5])

In [81]:
a[:,1]

array([2, 4, 5])

In [82]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [83]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print ('Our array is:' )
print (a )
print ('\n') 

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]




In [85]:
a[...,1]

array([2, 4, 5])

In [86]:
a[:,1]

array([2, 4, 5])

In [87]:
a[1,:]

array([3, 4, 5])

In [88]:
a[1,...]

array([3, 4, 5])

## Array Manipulation

In [89]:
a = np.arange(8)
print(a)

[0 1 2 3 4 5 6 7]


In [90]:
a.shape

(8,)

In [91]:
b = a.reshape(4,2)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [92]:
a = np.arange(8).reshape(2,4) 
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [107]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [108]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [109]:
a.transpose()

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [110]:
a=np.array(([1,2,3],[4,5,6]))
b=np.array(([7,8,0],[10,11,12]))

In [111]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  7,  8,  0],
       [ 4,  5,  6, 10, 11, 12]])

In [113]:
c=np.concatenate((a,b),axis=0)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  0],
       [10, 11, 12]])

In [114]:
np.delete(c,1,axis=0)

array([[ 1,  2,  3],
       [ 7,  8,  0],
       [10, 11, 12]])

In [115]:
np.delete(c,1,axis=1)

array([[ 1,  3],
       [ 4,  6],
       [ 7,  0],
       [10, 12]])

In [116]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
b

array([[ 7,  8,  0],
       [10, 11, 12]])

In [119]:
a=np.array(([1,2,3],[4,5,6],[3,4,2]))
a

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 2]])

In [120]:
a.diagonal()

array([1, 5, 2])

In [121]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
print(np.resize(a, (3,2)) )


[[1 2]
 [3 4]
 [5 6]]


In [123]:
print(np.append(a, [[7,8,9]],axis = 0))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [126]:
print (np.append(a, [[5,5,5],[7,8,9]],axis = 1))


[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [127]:
a = np.array([[1,2],[3,4],[5,6]]) 
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [128]:
print( np.insert(a,1,[11],axis = 0))


[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


In [131]:
print( np.insert(a,[1],[11],axis = 1))


[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [132]:
a = np.array([5,2,6,2,7,5,6,8,2,9]) 
u = np.unique(a) 
u

array([2, 5, 6, 7, 8, 9])

In [133]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 

In [134]:
print (np.stack((a,b),0)) 
print('\n-----------')
print (np.stack((a,b),1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

-----------
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [135]:
c = np.vstack((a,b)) 
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [136]:
c = np.hstack((a,b)) 
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [137]:
a = np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [138]:
np.split(a,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [139]:
a = np.arange(16).reshape(4,4) 
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [140]:
np.split(a,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [141]:
np.hsplit(a,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [142]:
b = np.vsplit(a,2) 
b

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

## Operators

In [143]:
a=np.array(([1,2,3],[4,5,6]))
b=np.array(([7,8,0],[10,11,12]))


In [144]:
a+b

array([[ 8, 10,  3],
       [14, 16, 18]])

In [145]:
np.add(a,b)

array([[ 8, 10,  3],
       [14, 16, 18]])

In [146]:
a-b

array([[-6, -6,  3],
       [-6, -6, -6]])

In [147]:
np.subtract(a,b)

array([[-6, -6,  3],
       [-6, -6, -6]])

In [148]:
a/b

<ipython-input-148-aae42d317509>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/b


array([[0.14285714, 0.25      ,        inf],
       [0.4       , 0.45454545, 0.5       ]])

In [149]:
np.divide(a,b)

<ipython-input-149-c364992e28ce>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(a,b)


array([[0.14285714, 0.25      ,        inf],
       [0.4       , 0.45454545, 0.5       ]])

In [150]:
a*b

array([[ 7, 16,  0],
       [40, 55, 72]])

In [151]:
np.multiply(a,b)

array([[ 7, 16,  0],
       [40, 55, 72]])

In [152]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [153]:
print(np.sum(a, axis=0))

[5 7 9]


In [154]:
print(np.sum(a, axis=1))

[ 6 15]


In [155]:
x = np.array(([1,2],[3,4])) 
print(x.shape,'\n')

(2, 2) 



In [156]:
y = np.expand_dims(x, axis = 0) 
print(y.shape,'\n')

(1, 2, 2) 



In [157]:
y = np.expand_dims(x, axis = 1) 
print(y.shape,'\n')

(2, 1, 2) 



In [159]:
x = np.arange(9).reshape(1,3,3) 
print(x)
print('\n',x.shape,'\n')

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]

 (1, 3, 3) 



In [160]:
y = np.squeeze(x) 
print(y.shape,'\n')

(3, 3) 



In [161]:
a,b=13,17
print (np.bitwise_and(13, 17))
print (np.bitwise_or(13, 17))
print (np.invert(np.array([13], dtype = np.uint8)) )
print (np.binary_repr(242, width = 8))
print (np.left_shift(10,2) )
print (np.right_shift(40,2) )

1
29
[242]
11110010
40
10


In [162]:
np.sin(30)

-0.9880316240928618

In [163]:
np.tan(45)

1.6197751905438615

In [164]:
np.floor(2.36)

2.0

In [165]:
np.round(2.36)

2.0

In [166]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [167]:
np.amin(a,1) 

array([3, 3, 2])

In [168]:
np.amin(a,0) 

array([2, 4, 3])

In [169]:
np.amax(a,1) 

array([7, 8, 9])

In [170]:
np.amin(a,0) 

array([2, 4, 3])

In [171]:
np.median(a, axis = 0) 

array([3., 4., 5.])

In [172]:
np.median(a, axis = 1) 

array([5., 4., 4.])

In [173]:
np.std([1,2,3,4])

1.118033988749895

In [174]:
np.var([1,2,3,4])

1.25

In [175]:
np.sort(a, axis = 0) 


array([[2, 4, 3],
       [3, 4, 5],
       [8, 7, 9]])

In [176]:
np.sort(a, axis = 1) 


array([[3, 5, 7],
       [3, 4, 8],
       [2, 4, 9]])

In [177]:
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

## String Functions


In [180]:
np.char.add(['hello'],[' biglearn']) 


array(['hello biglearn'], dtype='<U14')

In [181]:
np.char.multiply('Hello ',3)


array('Hello Hello Hello ', dtype='<U18')

In [183]:
np.char.center('hello', 20,fillchar = '*')


array('*******hello********', dtype='<U20')

In [184]:
np.char.capitalize('hello world')


array('Hello world', dtype='<U11')

In [185]:
np.char.title('hello how are you?')


array('Hello How Are You?', dtype='<U18')

In [186]:
np.char.lower(['HELLO','WORLD']) 


array(['hello', 'world'], dtype='<U5')

In [187]:
np.char.upper(['hello','world'])


array(['HELLO', 'WORLD'], dtype='<U5')

In [188]:
np.char.split ('hello how are you?') 


array(list(['hello', 'how', 'are', 'you?']), dtype=object)

In [190]:
np.char.join('-','dmy') 


array('d-m-y', dtype='<U5')

In [191]:
np.char.replace ('He is a good boy', 'is', 'was')


array('He was a good boy', dtype='<U17')

In [193]:
a = np.char.encode('hello', 'cp500') 
print( np.char.decode(a,'cp500'))

hello


## Linear Algebra

In [194]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 

In [195]:
np.dot(a,b) 

array([[37, 40],
       [85, 92]])

In [196]:
np.inner(np.array([1,2,3]),np.array([0,1,0])) 
# Equates to 1*0+2*1+3*0

2

In [197]:
print (np.matmul(a,b))

[[37 40]
 [85 92]]


In [198]:
print (np.linalg.det(a))

-2.0000000000000004


In [199]:
np.linalg.inv(a) 

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [201]:
np.linalg.svd(a)

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

In [203]:
np.linalg.norm(a)

5.477225575051661

## I/O with NumPy

In [204]:
a = np.array([1,2,3,4,5]) 
a

array([1, 2, 3, 4, 5])

In [205]:
np.save('outfile',a)

In [207]:
b = np.load('outfile.npy') 
print (b) 


[1 2 3 4 5]


In [208]:
np.savetxt('out.txt',a) 


In [209]:
b = np.loadtxt('out.txt') 
print (b) 

[1. 2. 3. 4. 5.]
