In [ ]:
عملیات های منطقی و ریاضیاتی با آرایه‌ها و ماتریسها، تبدیل های فوریه، عملیات های جبرخطی، توابع برای همه این موارد و توابع اعداد رندوم و…



In [2]:
!Pip install Numpy


  Using cached numpy-1.18.2-cp38-cp38-win_amd64.whl (12.8 MB)


In [3]:
import numpy as np

## NumPy - Ndarray Object


In [91]:
dt = np.dtype(np.int32) 
print (dt)

int32


In [93]:
a=np.array([1,5,8])
a

array([1, 5, 8])

In [94]:
a.dtype

dtype('int32')

In [89]:
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print (a)

[[1 2 3 4 5]]


In [106]:
#This array attribute returns the length of each element of array in bytes.

x = np.array([1,2,3,4,5], dtype = np.int8) 
print (x.itemsize)

1


## NumPy - Array From Numerical Ranges


In [8]:
np.array(range(15))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [90]:
a = np.array([1, 2, 3], dtype = complex) 
print (a)

[1.+0.j 2.+0.j 3.+0.j]


In [121]:
x = np.arange(10,20,2) 
print (x)

[10 12 14 16 18]


In [122]:
x = np.linspace(10,20,5) 
x

array([10. , 12.5, 15. , 17.5, 20. ])

In [123]:
x = np.linspace(10,20, 5, endpoint = False) 
x

array([10., 12., 14., 16., 18.])

In [124]:
x = np.linspace(1,2,5, retstep = True) 
x

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)

In [1]:
a = np.logspace(1,10,num = 10, base = 2) 
a

NameError: name 'np' is not defined

## NumPy - Array Creation Routines


In [107]:
np.empty([3,2], dtype = int) 


array([[0, 0],
       [0, 0],
       [0, 0]])

In [12]:
np.zeros((5,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [15]:
np.identity((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [172]:
np.full((3,4),0.2)
np.eye(4,4)
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## NumPy - Array Attributes


In [19]:
a=np.array(([7,9,5],[3,5,7]))
a[0,1]

9

In [20]:
a.shape

(2, 3)

In [21]:
len(a)

2

In [22]:
a.size

6

In [23]:
type(a)

numpy.ndarray

In [27]:
a.reshape(1,6)

array([[7, 9, 5, 3, 5, 7]])

In [39]:
a.resize((3,2))

In [35]:
a

array([[7, 9],
       [5, 3],
       [5, 7]])

In [40]:
a.reshape(2,3)

array([[7, 9, 5],
       [3, 5, 7]])

In [103]:
s = np.arange(24) 
print(s)
s.ndim 
s.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


(24,)

In [41]:
a.sum()

36

In [42]:
a.mean()

6.0

In [44]:
a.dtype

dtype('int32')

## NumPy - Array From Existing Data


In [110]:
# convert list to ndarray 
import numpy as np 

x = [1,2,3] 
a = np.asarray(x) 
a

array([1, 2, 3])

In [109]:
x = [1,2,3]
a = np.asarray(x, dtype = float) 
a

array([1., 2., 3.])

In [112]:
# ndarray from tuple 
x = (1,2,3) 
a = np.asarray(x) 
print (a)

[1 2 3]


In [113]:
# ndarray from list of tuples 
x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
a

array([(1, 2, 3), (4, 5)], dtype=object)

In [120]:
#This function builds an ndarray object from any iterable object.
li = range(5) 
it = iter(list)  
print(li)
# use iterator to create ndarray 
x = np.fromiter(it, dtype = float) 
x

range(0, 5)


array([0., 1., 2., 3., 4.])

## NumPy - Indexing & Slicing


In [126]:
a = np.arange(10) 
s = slice(2,7,2) 
a[s]

array([2, 4, 6])

In [127]:
a = np.arange(10) 
b = a[2:7:2] 
b

array([2, 4, 6])

In [128]:
a = np.arange(10) 
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
a = np.arange(10) 
a[2:5]

array([2, 3, 4])

In [131]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)  
print('-----------')
print (a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
-----------
[[3 4 5]
 [4 5 6]]


In [140]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print ('Our array is:' )
print (a )
print ('\n')  

print ('The items in the second column are:' ) 
print (a[...,1] )
print ('\n')  
print ('The items in the third column are:' ) 
print (a[...,2] )
print ('\n')  
# Now we will slice all items from the second row 
print ('The items in the second row are:' )
print (a[1,...] )
print ('\n')  
print ('The items in the third row are:' )
print (a[2,...] )
print ('\n')  
# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:') 
print (a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the third column are:
[3 5 6]


The items in the second row are:
[3 4 5]


The items in the third row are:
[4 5 6]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


In [141]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
y

array([1, 4, 5])

## NumPy - Array Manipulation


In [143]:
a = np.arange(8)
print(a)
print('-------------')
b = a.reshape(4,2)
print(b)

[0 1 2 3 4 5 6 7]
-------------
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [150]:
a = np.arange(8).reshape(2,4) 
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [151]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [49]:
a.transpose()

array([[7, 5, 5],
       [9, 3, 7]])

In [68]:
a=np.array(([1,2,3],[4,5,6]))
b=np.array(([7,8,0],[10,11,12]))

In [53]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  7,  8,  0],
       [ 4,  5,  6, 10, 11, 12]])

In [54]:
np.concatenate((a,b),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  0],
       [10, 11, 12]])

In [56]:

a

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
np.delete(a,1,axis=0)

array([[1, 2, 3]])

In [60]:
c=np.delete(a,2,axis=1)
c

array([[1, 2],
       [4, 5]])

In [61]:
c.diagonal()

array([1, 5])

In [193]:
a = np.array([[1,2,3],[4,5,6]]) 

print(a,'\n------')
print(np.resize(a, (3,2)) )

print('\n------')
print(np.append(a, [[7,8,9]],axis = 0))

print('\n------')
print (np.append(a, [[5,5,5],[7,8,9]],axis = 1))


[[1 2 3]
 [4 5 6]] 
------
[[1 2]
 [3 4]
 [5 6]]

------
[[1 2 3]
 [4 5 6]
 [7 8 9]]

------
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [199]:
a = np.array([[1,2],[3,4],[5,6]]) 
print(a,'\n---')

print( np.insert(a,1,[11],axis = 0))
print( np.insert(a,1,[11],axis = 1) )


[[1 2]
 [3 4]
 [5 6]] 
---
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [201]:
a = np.array([5,2,6,2,7,5,6,8,2,9]) 
u = np.unique(a) 
u

array([2, 5, 6, 7, 8, 9])

In [177]:
#his function joins the sequence of arrays along a new axis.
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 

print (np.stack((a,b),0)) 
print('\n-----------')
print (np.stack((a,b),1))


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

-----------
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [178]:
c = np.vstack((a,b)) 
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [179]:
c = np.hstack((a,b)) 
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [182]:
a = np.arange(9)
print(a)
b = np.split(a,3) 
b

[0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [185]:
a = np.arange(16).reshape(4,4) 
print(a,'\n-------')
b = np.hsplit(a,2) 
b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 
-------


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [186]:
b = np.vsplit(a,2) 
b

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

## NumPy - Broadcasting


In [69]:
a=np.array(([1,2,3],[4,5,6]))
b=np.array(([7,8,0],[10,11,12]))


In [70]:
a+b

array([[ 8, 10,  3],
       [14, 16, 18]])

In [71]:
a-b

array([[-6, -6,  3],
       [-6, -6, -6]])

In [72]:
np.add(a,b)

array([[ 8, 10,  3],
       [14, 16, 18]])

In [73]:
np.subtract(a,b)

array([[-6, -6,  3],
       [-6, -6, -6]])

In [74]:
a*b

array([[ 7, 16,  0],
       [40, 55, 72]])

In [75]:
np.multiply(a,b)

array([[ 7, 16,  0],
       [40, 55, 72]])

In [76]:
a/b

<ipython-input-76-aae42d317509>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/b


array([[0.14285714, 0.25      ,        inf],
       [0.4       , 0.45454545, 0.5       ]])

In [77]:
np.divide(a,b)

<ipython-input-77-c364992e28ce>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(a,b)


array([[0.14285714, 0.25      ,        inf],
       [0.4       , 0.45454545, 0.5       ]])

In [78]:
print(np.sum(a, axis=0))

[5 7 9]


In [79]:
print(np.sum(a, axis=1))

[ 6 15]


In [165]:
x = np.array(([1,2],[3,4])) 
print(x.shape,'\n')
y = np.expand_dims(x, axis = 0) 
print(y.shape,'\n')
z = np.expand_dims(x, axis = 1) 
print(z.shape,'\n')

(2, 2) 

(1, 2, 2) 

(2, 1, 2) 



In [171]:
x = np.arange(9).reshape(1,3,3) 
print(x)
print('\n',x.shape,'\n')
y = np.squeeze(x) 
print(y.shape,'\n')


[[[0 1 2]
  [3 4 5]
  [6 7 8]]]

 (1, 3, 3) 

(3, 3) 



In [81]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
np.tile(a, (4, 2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## NumPy -  Operators


In [209]:
 a,b=13,17
print (np.bitwise_and(13, 17))
print (np.bitwise_or(13, 17))
print (np.invert(np.array([13], dtype = np.uint8)) )
print (np.binary_repr(242, width = 8))
print (np.left_shift(10,2) )
print (np.right_shift(40,2) )


1
29
[242]
11110010
40
10


In [211]:
print (np.add(a,b) )


30


In [83]:
np.sin(30)

-0.9880316240928618

In [84]:
np.tan(60)

0.320040389379563

In [86]:
np.floor(2.36)

2.0

In [88]:
np.round(2.36)

2.0

In [229]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [230]:
np.amin(a,1) 


array([3, 3, 2])

In [231]:
np.amin(a,0) 


array([2, 4, 3])

In [233]:
np.amax(a, axis = 0)



array([8, 7, 9])

In [234]:
np.median(a, axis = 0) 


array([3., 4., 5.])

In [235]:
np.mean(a, axis = 1)


array([5., 5., 5.])

In [236]:
np.average([1,2,3, 4],weights = [4,3,2,1], returned = True)


(2.0, 10.0)

In [237]:
np.std([1,2,3,4])


1.118033988749895

In [238]:
np.var([1,2,3,4])


1.25

In [239]:
a = np.array([[3,7],[9,1]]) 
a

array([[3, 7],
       [9, 1]])

In [240]:
np.sort(a, axis = 0) 


array([[3, 1],
       [9, 7]])

In [241]:
np.argmax(a, axis = 0) 


array([1, 0], dtype=int64)

In [242]:
np.nonzero (a)


(array([0, 0, 1, 1], dtype=int64), array([0, 1, 0, 1], dtype=int64))

In [243]:
np.where(a > 3) 


(array([0, 1], dtype=int64), array([1, 0], dtype=int64))

In [244]:
np.mod(a,2) == 0 


array([[False, False],
       [False, False]])

## NumPy - String Functions


In [214]:
np.char.add(['hello'],[' xyz']) 


array(['hello xyz'], dtype='<U9')

In [215]:
np.char.multiply('Hello ',3)



array('Hello Hello Hello ', dtype='<U18')

In [216]:
np.char.center('hello', 20,fillchar = '*')


array('*******hello********', dtype='<U20')

In [217]:
np.char.capitalize('hello world')


array('Hello world', dtype='<U11')

In [218]:
np.char.title('hello how are you?')


array('Hello How Are You?', dtype='<U18')

In [220]:
np.char.lower(['HELLO','WORLD']) 


array(['hello', 'world'], dtype='<U5')

In [221]:
np.char.upper(['hello','world'])


array(['HELLO', 'WORLD'], dtype='<U5')

In [222]:

np.char.split ('hello how are you?') 


array(list(['hello', 'how', 'are', 'you?']), dtype=object)

In [223]:
np.char.splitlines('hello\nhow are you?') 


array(list(['hello', 'how are you?']), dtype=object)

In [224]:
np.char.strip('ashok arora','a') 


array('shok aror', dtype='<U11')

In [225]:
np.char.join(':','dmy') 


array('d:m:y', dtype='<U5')

In [226]:
np.char.replace ('He is a good boy', 'is', 'was')


array('He was a good boy', dtype='<U17')

In [227]:
a = np.char.encode('hello', 'cp500') 
print( np.char.decode(a,'cp500'))

hello


In [228]:
a = np.char.encode('hello', 'cp500') 
print (a)

b'\x88\x85\x93\x93\x96'


## NumPy - Linear Algebra


In [247]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [248]:
np.inner(np.array([1,2,3]),np.array([0,1,0])) 
# Equates to 1*0+2*1+3*0

2

In [249]:
a = [[1,0],[0,1]] 
b = [[4,1],[2,2]] 
print (np.matmul(a,b))

[[4 1]
 [2 2]]


In [250]:
a = np.array([[1,2], [3,4]]) 
print (np.linalg.det(a))

-2.0000000000000004


In [251]:
x = np.array([[1,2],[3,4]]) 
np.linalg.inv(x) 

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## I/O with NumPy


In [252]:
import numpy as np 
a = np.array([1,2,3,4,5]) 
np.save('outfile',a)

In [253]:
import numpy as np 
b = np.load('outfile.npy') 
print (b) 

[1 2 3 4 5]


In [254]:
a = np.array([1,2,3,4,5]) 
np.savetxt('out.txt',a) 
b = np.loadtxt('out.txt') 
print (b) 

[1. 2. 3. 4. 5.]
